### ISSUE TITLE
Error in if (max(abs(dXs)) < tol) rebalance <- FALSE else if (!is.na(tol.p) &&  

### ISSUE THREAD

**Issue by MislavSag** [enricoschumann/PMwR#3]
I contuined with my momentum backtest and get some error again which I can' debug.

Here is exampled code:
```
library(data.table)
library(xts)
library(PMwR)
prices = fread("https://snpmarketdata.blob.core.windows.net/test/prices.csv")
prices = as.xts.data.table(prices)
timestamp <- index(prices)
instrument <- colnames(prices)
mom = function(P, k) {
  print("TEST")
  o <- order(P[nrow(P), ]/P[1, ], decreasing = TRUE)
  w <- numeric(ncol(P))
  w[o[1:k]] <- 1/k
  w
}
mom.latest <- mom(head(coredata(prices), 250), 10)
signal <- function(fun, ...) {
  print("HERE")
  P <- Close(n = 250)
  fun(P, ...)
}
bt.mom <- btest(prices = list(coredata(prices)),
                signal = signal,
                do.signal = "lastofmonth",
                convert.weights = TRUE,
                initial.cash = 1000,
                k = 2,
                fun = mom,
                b = 250,
                timestamp = timestamp,
                instrument = instrument)
```
Here is the output
```
[1] "2000-02-28 20:00:00 UTC"
[1] "2000-03-30 20:00:00 UTC"
[1] "2000-04-27 19:00:00 UTC"
[1] "2000-05-30 19:00:00 UTC"
[1] "2000-06-29 19:00:00 UTC"
[1] "2000-07-28 19:00:00 UTC"
[1] "2000-08-30 19:00:00 UTC"
[1] "2000-09-28 19:00:00 UTC"
[1] "2000-10-30 20:00:00 UTC"
[1] "2000-11-29 20:00:00 UTC"
[1] "2000-12-28 20:00:00 UTC"
[1] "2001-01-30 20:00:00 UTC"
Error in if (max(abs(dXs)) < tol) rebalance <- FALSE else if (!is.na(tol.p) &&  : 
  missing value where TRUE/FALSE needed
```

**Comment by enricoschumann** [comment]
I cannot reproduce the error with your example code. But that error message is a common issue: some computation you did returned `NA`. Later, an `if` clause that relies on that computation does not evaluate to a logical value TRUE or FALSE. Most likely your signal function returned `NA` instead of a finite numeric value.

For debugging, I'd try something like this:

    signal <- function(fun, ...) {
      print("HERE")
      P <- Close(n = 250)
      w <- fun(P, ...)
      if (any(!is.finite(w))) {
         browser()
      }
      w
    }

That will stop the evaluation in a browser when a non-finite weight occurs, and you can investigate interactively why it happened.

**Comment by MislavSag** [comment]
I have updated R to latest version (4.3.2.) and all packages and it works now.
I am not sure what was the problem, but it seems the package requires latest versions.
