### ISSUE TITLE
Cont last issue

### ISSUE THREAD

**Issue by MislavSag** [enricoschumann/PMwR#4]
Sorry, but I have similar issue again. I have ran the same codeas in previous issue on the larger dataset :
```
# create signal function
mom = function(P, k) {
  # P = coredata(prices["2004-02-26 20:00:00 UTC/2004-03-26 20:00:00 UTC"])
  o <- order(P[nrow(P), ]/ P[1, ], decreasing = TRUE)
  w <- numeric(ncol(P))
  w[o[1:k]] <- 1/k
  w
}
mom.latest <- mom(head(coredata(prices), 250), 10)
signal <- function(fun, ...) {
  print("Debug 1")
  print(Timestamp())
  # if (as.character(Timestamp()) == '"1998-05-28 19:00:00 UTC"') print(Close(n = 250))
  P <- Close(n = 250)
  print("Debug 2")
  w = fun(P, ...)
  print(all(is.finite(w)))
  print(w)
  # if (any(!is.finite(w))) {
  #   print("problem!")
  # }
}
bt.mom <- btest(prices = list(coredata(P)),
                signal = signal,
                do.signal = "lastofmonth",
                convert.weights = TRUE,
                initial.cash = 1000,
                k = 3,
                fun = mom,
                b = 250,
                timestamp = timestamp,
                instrument = instrument)
```
and I get error :
```
Error in if (max(abs(dXs)) < tol) rebalance <- FALSE else if (!is.na(tol.p) &&  : 
  missing value where TRUE/FALSE neede
```
I tested if all values are finite in w as you see above and they are. 
If I uncomment this part:
```
  # if (any(!is.finite(w))) {
  #   print("problem!")
  # }
```
it doesn't return an error. Weird behavior.

I have added the dataset on the cloud. You can download it but it is larger file this time:
https://snpmarketdata.blob.core.windows.net/test/prices_large.csv

**Comment by enricoschumann** [comment]
(A note before all else: nothing I see here is an issue of `btest`; the function behaves as expected.)

I start with the easy part: You get _no_ error if you say

    if (any(!is.finite(w))) {
        print("problem!")
    }

at the end of the signal function. That is because the condition is never `TRUE`, and you always get the (implicit) `else` clause, which is `NULL`. If the signal function in `btest` returns `NULL`, it means to keep the current position. (That is a documented feature.) So you will always keep your current position, which is no position at all. Check `journal(bt.mom)` after you called `btest`, and you should see `no transactions`.

Your actual error is the result of `NA`s in your data. Many of the series you have do not span the whole time period. So you'll need to tell `btest` when it can trade a particular asset. Your backtest breaks down at around `2000-05-30 19:00:00 UTC`. When I call a browser then, I see:

    > Portfolio()[, Portfolio()>0, drop = FALSE]
    ##          axe     farc      rti
    ## [1,] 9.709327 13.23844 21.94994
  
I check the prices of those assets:

    ##                          axe farc   rti
    ##                 ...                    
    ## 2000-05-30 14:00:00 19.26546   NA 13.00
    ## 2000-05-30 15:00:00 19.66224   NA 13.06
    ## 2000-05-30 16:00:00 19.61973   NA 12.94
    ## 2000-05-30 17:00:00 19.44259   NA 13.00
    ## 2000-05-30 18:00:00 19.26546   NA 13.00
    ## 2000-05-30 19:00:00 19.35048   NA 13.13

So `btest` has a position, but cannot value it (any more).  A way to handle missing values is described in [Backtests with time-varying asset universes](http://www.enricoschumann.net/notes/backtests-with-time-varying-universes.html) .

**Comment by MislavSag** [comment]
I have read the notes now. I have created an active data frame as you think in the example. But I think the problem is different.

Strategy buys an asset at the beginning of the month and during the month prices become NA. The reason is probably that the stock is delisted. I suppose I should sell when something like this happens but I am not sure how to sell in that case.

I tried to remove it this doesn;t work:
```
signal <- function(active, fun, ...) {
  print(Timestamp())
  j <- Timestamp() >= active[["start"]] &
    Timestamp() <= active[["end"]]
  Pj <- Close(n = 250)[, j]
  portfolio_stocks = colnames(Portfolio())[Portfolio() > 0]
  stock_sell_delisting = sell_before_removed[instrument %in% portfolio_stocks &
                                               Timestamp() >= sell_before_removed$end,]
  print(stock_sell_delisting)
  print(nrow(stock_sell_delisting))
  if (nrow(stock_sell_delisting) > 0) {
    print(dim(Pj))
    Pj = Pj[, -!(colnames(Pj) == stock_sell_delisting$instrument)]
    print(dim(Pj))
  }
  wj = fun(Pj, ...)
  w <- numeric(length(j))
  w[j] <- wj
  w
}
```

**Comment by enricoschumann** [comment]
The tricky question is how much knowledge you can assume when running a backtest.  How far in advance do you know that a stock is going to disappear?  When you answer that question, you are always running the risk of, at a certain point in time, using knowledge that was only available later.

As far as I am aware of studies, when a stock disappears, its usually for a bad reason; for example

    @Article{shumway1997,
      author       = {Tyler Shumway},
      title        = {The Delisting Bias in CRSP Data},
      journaltitle = {Journal of Finance},
      year         = 1997,
      review       = {list of delisting returns by PERMNO},
      keywords     = {CRSP}
    }

As for handling this in `btest`: You just need to choose appropriate rebalancing dates (or active start/end dates). Suppose that last price of stock X is on 15 March: before, you have good prices; from 16 March it's only NA. Then when you rebalance on 15 March and mark the stock as inactive from that date: i) you'll pick a new portfolio, and X will get a weight of zero, ii) `btest` sells X at the last price (on March 15) and never touches it again.

**Comment by MislavSag** [comment]
This i exactly what I was thinking. But in that case I should check data on every hour and can't use `lastofmonth` option for rebalancing because till end of the month came, the stock is already delisted (or bankrupt or somthing else). It is tricky task but in my opinion better than just including all companies that survived for sure.

I will few solutions today and close if one of them would work.

**Comment by MislavSag** [comment]
Is there any other place where can I ask additional questions about the package? For exmaple, I would like to know what is recomendened way to include additional data. Say I want volume columne too, shoule I define it outside the signal function?

**Comment by enricoschumann** [comment]
Regarding `lastofmonth`: You could expand the list of rebalancing times, e.g.

```r
library("datetimeutils")
t.rebalance <- nth_day(index(prices), period = "month", n = "last", index = TRUE)
## [1]   140   280   441   574   728 ....

## add arbitrary rebalancing time, e.g. 999
t.rebalance <- sort(c(999, t.rebalance)
```
Then pass `t.rebalance` as argument `do.signal`. But simpler might be to "throw away" a few observations. Again, suppose that some stock drops from the dataset in mid-March. Just set it to "not active" at the end of February. Then you can keep rebalancing at the end of the month.

Regarding questions: my preferred place would be R-SIG-Finance ( https://stat.ethz.ch/mailman/listinfo/r-sig-finance ), which I also read and where I answer questions (if I can).

**Comment by MislavSag** [comment]
I have sen a subscription request to r-sig-finance.

I haven't tried your approach yet, but I am sure it will work if I do it right.

Acording adding volume (or some other variable) to btest data, I see only two solutions:

**Supplemental Analysis**: Use the volume data for supplemental analysis outside of the btest function. This involves analyzing the volume data separately to inform my trading signals, which I then feed into btest. This is a two-step process where the volume analysis is decoupled from the backtesting process.

**Custom Function Modification**: I could modify the btest function or write a wrapper around it to incorporate volume data. This is more complex and requires a deep understanding of both the btest function and your specific requirements.

**Comment by enricoschumann** [comment]
You can pass volume information to `btest` and then process it in `signal`. I'd collect volume in a series that is in sync with prices (i.e. the _n_-th observations of prices and volume correspond to the same timestamp). Then pass volume as an argument to to `btest` and access it with `Time()`. Here is a simple example:

    library("PMwR")
    prices <- 101:105
    volume <-   1:  5
    data.frame(prices, volume)
    ##   prices volume
    ## 1    101      1
    ## 2    102      2
    ## 3    103      3
    ## 4    104      4
    ## 5    105      5

    signal <- function(volume) {
        message()
        cat("Time", Time(), "\n",
            "Price", Close(), "\n",
            "Volume", volume[Time()], "\n")
        1
    }
    btest(prices, signal = signal, volume = volume)
    ## Time 1 
    ##  Price 101 
    ##  Volume 1 
    ## 
    ## Time 2 
    ##  Price 102 
    ##  Volume 2 
    ## 
    ## Time 3 
    ##  Price 103 
    ##  Volume 3 
    ## 
    ## Time 4 
    ##  Price 104 
    ##  Volume 4 
    ## initial wealth 0  =>  final wealth  3 

Of course, you can also access more than a single data point. For instance, `volume[Time(n=5)]` would give you the previous 5 volume observations.

**Comment by MislavSag** [comment]
@enricoschumann , thank a lost for all help/ It seems everything is working now. It's nice to add btest and PMwR to quant arsenal.
